In [11]:

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Loading in Data
Cleaned_Job_df = pd.read_csv("Joined_Data/Cleaned_New_Joined_Data.csv")
Cleaned_Job_df.head()

,id,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,title,...,typescript,unix,unix/linux,vb.net,vba,visio,visual_basic,vue,vue.js,word
0,2,21 to 23,an hour,22.0,21.0,23.0,22.0,NaN,45760.0,Legal Data Analyst,...,0,0,0,0,0,0,0,0,0,0
1,11,100K to 140K,a year,120000.0,100000.0,140000.0,NaN,120000.0,120000.0,Lead Data Analyst,...,0,0,0,0,0,0,0,0,0,0
2,20,25 to 26,an hour,25.5,25.0,26.0,25.5,NaN,53040.0,Junior Data Analyst,...,0,0,0,0,0,0,0,0,0,1
3,58,25,an hour,25.0,NaN,NaN,25.0,NaN,52000.0,Healthcare Data Analyst,...,0,0,0,0,0,0,0,0,0,0
4,63,73570 to 110350,a year,91960.0,73570.0,110350.0,NaN,91960.0,91960.0,Program Management Data Analyst,...,0,0,0,0,0,0,0,0,0,0

In [36]:
#Creating a model
L_R = LinearRegression()

Train = Cleaned_Job_df.loc[:,"airflow" : "word"]

In [48]:
#Assigning X and Y arays.

skills = Cleaned_Job_df.loc[:, "airflow" : "word"]
schedule_type = pd.get_dummies(Cleaned_Job_df["schedule_type"], drop_first=True)
work_from_home = ["work_from_home"]

# create a linear regression model and fit it to the training data
L_R= LinearRegression()

x = pd.concat Cleaned_Job_df(["skills", "schedule_type", "work_from_home"], axis=1)
y = Cleaned_Job_df["salary_standardized"]

# split data into training and testing sets
x_Train, x_test, y_Train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# create a linear regression model and fit it to the training data
L_R.fit(x_Train, y_Train)

SAMPLE CODE
# print the R-squared value of the model on the test set
#print(f"R-squared value: {L_R.score(x_test, y_test)}")
#print(f"Coefficients: {L_R.coef_}")

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

In [31]:
L_R.fit((x_Train, y_Train))

# (Train, Cleaned_Job_df ["salary_standardized"])
#L_R.score(Train, Cleaned_Job_df["salary_standardized"])

NameError: name 'x_Train' is not defined

In [29]:
L_R= LinearRegression()

predicted = L_R.predict(Train)

actual = Cleaned_Job_df["salary_standardized"]

plot1 = sns.histplot(data = predicted, kde = True, bins = 10)
plot1.set(xlim = (20_000, 250_000))
plot1.set(ylim = (0, 2500))
plot1.set_title("Linear Regression for Salary Standardized")

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.